{
 "title": "Momo-store dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Requests count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(requests_count{job=\"backend\"})",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Dumplings listing count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "max(dumplings_listing_count{job=\"backend\"})",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Backend status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"backend\"})",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(scrape_duration_seconds{job=\"backend\"})",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Frontend NGINX status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nginx_up{job=\"frontend\"})",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "description": "Node memory utilisation",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}