---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: node-drainer
  name: node-drainer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-drainer
  namespace: node-drainer
  labels:
    app.kubernetes.io/name: node-drainer
    app.kubernetes.io/instance: node-drainer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-drainer
      app.kubernetes.io/instance: node-drainer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-drainer
        app.kubernetes.io/instance: node-drainer
    spec:
      hostPID: true
      hostIPC: true
      initContainers:
        - name: node-drainer-init
          image: "cr.yandex/yc/mk8s-openssl:stable"
          imagePullPolicy: Never
          env:
            - name: DEBUG
              value: ""
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_DRAINER_SCRIPT
              value: |
                #!/bin/bash
                set -eo pipefail

                NODE_NAME=${NODE_NAME:-$(/usr/bin/hostname -s)}
                KUBECONFIG=${KUBECONFIG:-/etc/kubernetes/kubelet-kubeconfig.conf}
                KUBECTL=${KUBECTL:-"/home/kubernetes/bin/kubectl"}
                export KUBECONFIG
                CORDONED_FILE="/var/lib/node-drainer/cordoned-by-node-drainer"

                ### expects the list of pids of running processes and waits for them to finish
                waitall() {
                    local pids alive_pids timeout
                    pids="$1"
                    timeout=150 #approx 15 seconds
                    while [[ $timeout -gt 0 ]]; do
                        alive_pids=""
                        for pid in $pids; do
                            if /usr/bin/kill -0 "$pid" 2>/dev/null; then
                                alive_pids="$alive_pids $pid"
                            elif wait "$pid"; then
                                :
                            else
                                echo "Process $pid failed" >&2
                            fi
                        done
                        if [[ -z "$alive_pids" ]]; then
                            break
                        fi
                        pids="$alive_pids"
                        timeout=$(( timeout - 1 ))
                        sleep 0.1
                    done
                }

                ### debuffs the previously set cordon status
                public_uncordon() {
                    if [[ -f "$CORDONED_FILE" ]]; then
                        $KUBECTL uncordon "$NODE_NAME" || /usr/bin/true
                        /usr/bin/rm -f "$CORDONED_FILE"
                    fi
                }

                ### sets cordon status to the node and removes node hosted pods except DaemonSets
                public_drain() {
                    local pod ns current_ns pod_list pids
                    $KUBECTL cordon "$NODE_NAME"
                    touch "$CORDONED_FILE"
                    while read ns pod; do
                        if [[ "$ns" != "$current_ns" ]]; then
                            if [[ -n "$pod_list" ]]; then
                                $KUBECTL -n "$current_ns" delete pods --force --grace-period=0 $pod_list &
                                pids="$pids $!"
                                /usr/bin/sleep 0.1
                            fi
                            current_ns="$ns"
                            pod_list="$pod"
                        else
                            pod_list="$pod_list $pod"
                        fi
                    done < <($KUBECTL get pods -A --field-selector spec.nodeName="$NODE_NAME" \
                        -o jsonpath='{range .items[?(@.metadata.ownerReferences[0].kind!="DaemonSet")]}{@.metadata.namespace}{" "}{@.metadata.name}{"\n"}{end}' \
                        | /usr/bin/sort)
                    if [[ -n "$current_ns" ]]; then
                        $KUBECTL -n "$current_ns" delete pods --force --grace-period=0 $pod_list &
                        pids="$pids $!"
                    fi
                    waitall "$pids"
                }

                for cmd in $@; do "public_$cmd"; done

            - name: NODE_DRAINER_SERVICE
              value: |
                [Unit]
                Description=Pod draining service
                Requires=network.target
                DefaultDependencies=no
                Before=shutdown.target reboot.target
                Wants=network-online.target
                After=network-online.target

                [Service]
                Type=oneshot
                RemainAfterExit=true
                TimeoutStopSec=20
                ExecStart=/home/kubernetes/bin/node-drainer.sh uncordon
                ExecStop=/home/kubernetes/bin/node-drainer.sh drain

                [Install]
                WantedBy=multi-user.target

          command:
            - /bin/bash
            - -c
            - |
              [[ -z "$DEBUG" ]] || set -x
              set -eo pipefail
              NS_HOME=${NS_HOME:-/var/lib/node-drainer}
              echo "$NODE_DRAINER_SCRIPT" > /mnt/home/kubernetes/bin/node-drainer.sh
              /usr/bin/chmod +x /mnt/home/kubernetes/bin/node-drainer.sh
              echo "$NODE_DRAINER_SERVICE" > "$NS_HOME/node-drainer.service"
              /usr/bin/nsenter --target 1 --mount --uts --ipc --net --pid -- /bin/bash -e <<EOF
              [[ -z "$DEBUG" ]] || set -x
              mv "$NS_HOME/node-drainer.service" /etc/systemd/system/node-drainer.service
              /usr/bin/systemctl daemon-reload
              /usr/bin/systemctl enable --now node-drainer.service
              EOF

          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: var-lib-node-drainer
              mountPath: /var/lib/node-drainer
            - name: home-kubernetes-bin
              mountPath: /mnt/home/kubernetes/bin
      containers:
        - name: node-drainer-sleep
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            privileged: false
          image: "cr.yandex/yc/mk8s-openssl:stable"
          imagePullPolicy: Never
          command: [ "/usr/bin/sleep", "inf" ]
      volumes:
        - name: var-lib-node-drainer
          hostPath:
            path: /var/lib/node-drainer
            type: DirectoryOrCreate
        - name: home-kubernetes-bin
          hostPath:
            path: /home/kubernetes/bin
            type: Directory
      tolerations: []
...