{{- if .Values.podDisruptionBudget.enabled }}
{{- $replicas := .Values.replicaCount | int }}
{{- if .Values.autoscaling.enabled }}{{ $replicas = .Values.autoscaling.minReplicas | int }}{{ end }}
{{- if gt $replicas 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
